Repository Chillkongju/Frontend, pull requests merged in 2025-07, with the labels that each got.

#8 [feat/#7] 문화생활 추천 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/example/baba/MainActivity.kt
  app/src/main/java/com/example/baba/ui/recommendation/RecommendatinoScreen.kt
  app/src/main/java/com/example/baba/ui/recommendation/RecommendationScreen.kt
  app/src/main/res/drawable/book_poster_1.jpg
  app/src/main/res/drawable/book_poster_2.jpg
  app/src/main/res/drawable/movie_poster_1.jpeg
  app/src/main/res/drawable/movie_poster_2.jpeg
  app/src/main/res/drawable/recommend_book.png
  app/src/main/res/drawable/recommend_movie.png
  app/src/main/res/drawable/recommend_show.png
  app/src/main/res/drawable/show_poster_1.jpg
  app/src/main/res/drawable/show_poster_2.jpg
  gradle/libs.versions.toml
Labels: Chore, Feat

#11 Feat: 시작 화면 구현
  app/src/main/java/com/example/baba/MainActivity.kt
  app/src/main/java/com/example/baba/ui/auth/Splash.kt
  app/src/main/res/drawable/main_logo.png
  app/src/main/res/drawable/sub_logo.png
Labels: Feat

#14 [feat/#9] 친구 피드 화면 구현
  app/src/main/java/com/example/baba/ui/friends/FriendsScreen.kt
  app/src/main/java/com/example/baba/ui/theme/Color.kt
  app/src/main/res/drawable/friend_book_poster_1.jpeg
  app/src/main/res/drawable/friend_movie_poster_1.jpeg
  app/src/main/res/drawable/friend_movie_poster_2.jpg
  app/src/main/res/drawable/friend_show_poster_1.webp
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_comment_send.xml
  app/src/main/res/drawable/ic_default_profile.png
  app/src/main/res/drawable/ic_like_filled.xml
  app/src/main/res/drawable/ic_like_outline.xml
  app/src/main/res/drawable/ic_rating_button_arrow.xml
  app/src/main/res/drawable/ic_rating_button_star.xml
  app/src/main/res/drawable/user_profile_1.jpg
Labels: Feat

#21 [feat/#20] 로그인 및 회원가입 API 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/baba/data/auth/AuthApi.kt
  app/src/main/java/com/example/baba/data/auth/AuthModels.kt
  app/src/main/java/com/example/baba/data/network/RetrofitInstance.kt
  app/src/main/java/com/example/baba/ui/auth/LoginScreen.kt
  app/src/main/java/com/example/baba/ui/auth/SignupScreen.kt
  gradle/libs.versions.toml
Labels: Feat

#36 feat: 내 기록 단일 조회 화면 구현 (#35)
  app/src/main/java/com/example/baba/ui/record/Record.kt
  app/src/main/java/com/example/baba/ui/record/RecordDetailScreen.kt
Labels: Feat

#37 [feat/#25] 문화생활 기록하기 API 이미지 추가, 별점 타입 수정
  app/src/main/java/com/example/baba/data/record/DiaryModels.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsScreen.kt
  app/src/main/java/com/example/baba/ui/home/CreateActivity.kt
  app/src/main/java/com/example/baba/ui/home/CreateDetailScreen.kt
  app/src/main/java/com/example/baba/ui/home/CreateScreen.kt
Labels: Feat

#39 [feat/#27] 문화생활 기록 전체 조회 API 연동
  app/src/main/java/com/example/baba/data/record/DiaryApi.kt
  app/src/main/java/com/example/baba/data/record/DiaryModels.kt
  app/src/main/java/com/example/baba/data/record/WatchedDataManager.kt
  app/src/main/java/com/example/baba/ui/home/CreateActivity.kt
  app/src/main/java/com/example/baba/ui/home/CreateDetailScreen.kt
  app/src/main/java/com/example/baba/ui/home/CreateScreen.kt
  app/src/main/java/com/example/baba/ui/home/HomeScreen.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordList.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordScreen.kt
Labels: Feat

#40 Feat/34 친구 프로필 화면 언팔로우 기능
  app/build.gradle.kts
  app/src/main/java/com/example/baba/ui/friends/FriendsProfileScreen.kt
Labels: Feat

#43 [feat/#42] 문화생활 기록 단일 조회 API 연동
  app/build.gradle.kts
  app/src/main/java/com/example/baba/MainActivity.kt
  app/src/main/java/com/example/baba/ui/home/CreateActivity.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordList.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordScreen.kt
  app/src/main/java/com/example/baba/ui/record/Record.kt
Labels: Feat

#44 [feat/#31] 팔로우 API 연동
  app/src/main/java/com/example/baba/data/friends/FriendsApi.kt
  app/src/main/java/com/example/baba/data/friends/FriendsModels.kt
  app/src/main/java/com/example/baba/data/network/RetrofitInstance.kt
  app/src/main/java/com/example/baba/ui/friends/FollowScreen.kt
Labels: Feat

#45 [feat#28] 내 정보 조회 API 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/baba/App.kt
  app/src/main/java/com/example/baba/MainActivity.kt
  app/src/main/java/com/example/baba/data/member/MemberApi.kt
  app/src/main/java/com/example/baba/data/member/MemberModels.kt
  app/src/main/java/com/example/baba/data/network/RetrofitInstance.kt
  app/src/main/java/com/example/baba/ui/home/CreateActivity.kt
  app/src/main/java/com/example/baba/ui/home/HomeScreen.kt
  app/src/main/java/com/example/baba/ui/profile/EditProfileScreen.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordList.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordScreen.kt
  gradle/libs.versions.toml
Labels: Feat

#55 [feat/#54] 일일 문화생활 추천 전체 조회 API 연동
  app/src/main/java/com/example/baba/data/network/RetrofitInstance.kt
  app/src/main/java/com/example/baba/data/recommendation/RecommendationApi.kt
  app/src/main/java/com/example/baba/data/recommendation/RecommendationModels.kt
  app/src/main/java/com/example/baba/ui/home/CreateDetailScreen.kt
  app/src/main/java/com/example/baba/ui/record/RecordDetailScreen.kt
Labels: Feat

#59 [feat/#58] 문화생활 기록 좋아요 API 연동
  app/src/main/java/com/example/baba/data/love/LoveApi.kt
  app/src/main/java/com/example/baba/data/love/LoveModels.kt
  app/src/main/java/com/example/baba/data/network/RetrofitInstance.kt
  app/src/main/java/com/example/baba/ui/record/RecordDetailScreen.kt
Labels: Feat

#65 [feat/#64] 월별 문화생활 추천 전체 조회 API 연동
  app/src/main/java/com/example/baba/data/recommendation/CategoryRecommendationResponse.kt
  app/src/main/java/com/example/baba/data/recommendation/RecommendationApi.kt
  app/src/main/java/com/example/baba/ui/recommendation/RecommendationScreen.kt
Labels: Feat

#74 [feat/#73] 친구 기록 화면에서 카테고리 선택 시 기록 목록으로 이동
  app/src/main/java/com/example/baba/ui/friends/FriendsProfileScreen.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsRecordList.kt
Labels: Feat

#76 [refactor#75] 친구 피드 더미 데이터 변경
  app/src/main/java/com/example/baba/ui/auth/LoginScreen.kt
  app/src/main/java/com/example/baba/ui/friends/FollowScreen.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsProfileScreen.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsRecordList.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsScreen.kt
Labels: Refactor

#82 [design/#81] 문화생활 기록 카드 디자인 수정
  app/src/main/java/com/example/baba/MainActivity.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsProfileScreen.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsRecordList.kt
  app/src/main/java/com/example/baba/ui/friends/FriendsScreen.kt
  app/src/main/java/com/example/baba/ui/recommendation/RecommendationScreen.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordList.kt
  app/src/main/java/com/example/baba/ui/record/MyRecordScreen.kt
  app/src/main/java/com/example/baba/ui/record/RecordDetailScreen.kt
Labels: Design

#84 [fix/#83] 내 문화생활 기록 삭제가 안 되는 문제 해결
  app/src/main/java/com/example/baba/ui/record/RecordDetailScreen.kt
Labels: Fix
